---
title: "Animated Visualizations of Machine Learning Algorithms"
output: 
   rmdformats::material:
      self_contained: false
      thumbnails: false
      lightbox: false
      gallery: false
      highlight: tango
      include:
         after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Machine Learning Animations

> Understanding machine learning through beautiful algorithm animations

Here we present beautiful **animated visualizations** for some popular **Machine Learning** algorithms, built with the `R` package `animation`. These animations help to understand algorithm iterations and hyper-parameter tuning.

The source code is available on **[GitHub](https://github.com/davpinto/ml-simulations)**.

# Gradient Boosting Machine Iterations

Classification **Decision Boundary** of the **Gradient Boosting Machine** (GBM) from the `R` package `xgboost` as boosting iterations proceed.

<iframe src="./simul/xgb-iterations/index.html" frameborder="0" height="600" width="100%"></iframe>

*__[+ Source Code](https://github.com/davpinto/ml-simulations/tree/master/simulations/xgb-iterations)__*

----

# K-Nearest Neighbors Classifier

Analysing how the the number of nearest neighbors $k$ affects the classification **Decision Boundary** of the **KNN** algorithm from the `R` package [fastknn](https://davpinto.github.io/fastknn). We consider 2 probability estimators for the class membership probabilities: a *voting rule* and a *weighted voting rule* (shrinkage estimator).

<iframe src="./simul/knn-decision/index.html" frameborder="0" height="600" width="100%"></iframe>

*__[+ Source Code](https://github.com/davpinto/ml-simulations/tree/master/simulations/knn-decision)__*

----

# Expectation-Maximization Algorithm

**Gaussian Mixture Model** (GMM) fitted by **Expectation-Maximization** (EM) algorithm with random initialization.

Coming soon...

----

# Gaussian Mixture Density

**Density** estimation using a GMM with 7 components. Model fitting is performed by **Expectation-Maximization** algorithm with randomly assigned initial parameters. Positive definiteness of covariance matrix is achieved replacing the unrestricted maximum likelihood estimator by *Ledoit-Wolf* **shrinkage estimator**.

<iframe src="./simul/gmm-density/index.html" frameborder="0" height="450" width="100%"></iframe>

*__Source Code__* is not available yet.

----

# Regularized Extreme Learning Machine

Classification **Decision Boundary** of a *Single Layer Feedforward Network* (with 150 randomly assigned hidden neurons) trained by **Extreme Learning Machine** (ELM) algorithm considering ridge regression instead of ordinary least squares estimation. The larger the penalty parameter, the greater the amount of smoothing.

<iframe src="./simul/elm-regularization/index.html" frameborder="0" height="600" width="100%"></iframe>

*__[+ Source Code](https://github.com/davpinto/ml-simulations/tree/master/simulations/elm-regularization)__*

----

# Image Segmentation with K-Means

Image pixels grouping into k different clusters using the k-means algorithm. A different color is assigned for each cluster. This simulation is based on the following post: [R-bloggers](http://www.r-bloggers.com/r-k-means-clustering-on-an-image/).

<iframe src="./simul/kmeans-segmentation/index.html" frameborder="0" height="600" width="100%"></iframe>

*__[+ Source Code](https://github.com/davpinto/ml-simulations/tree/master/simulations/kmeans-segmentation)__*

----

# Image Reconstruction with Principal Components Analysis

Image reconstruction using the k first principal components (PCs).

<iframe src="./simul/pca-reconstruction/index.html" frameborder="0" height="600" width="100%"></iframe>

*__[+ Source Code](https://github.com/davpinto/ml-simulations/tree/master/simulations/pca-reconstruction)__*

----
